# Generated by Django 3.2.7 on 2021-09-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Movie_Name',
                'verbose_name_plural': 'Movies',
                'db_table': 'movie',
            },
        ),
    ]
